### ISSUE TITLE
Add PAPI placeholders for plugins

### ISSUE THREAD

**Issue by NoltoxGit** [Azuriom/AzLink#16]
🇫🇷 **Bonjour, me voici avec une nouvelle suggestion !**
Je me suis rappelé qu'[AzLink](https://github.com/Azuriom/AzLink) proposait un placeholders pour la monnaie de la boutique définie dans le Panel Admin, donc ça m'a donné une idée de placeholders qui en aiderait plus d'un avec le plugin [Vote d'Azuriom](https://github.com/Azuriom/Plugin-Vote), je m'explique,
L'idée que j'ai eu ce serait d'ajouter différents placeholders en lien avec les votes, telles que :

- Un placeholders permettant de savoir le délai d'un vote. (`%azlink_vote_ID_cooldown%`)
» Si vote disponible, résultat = `True`
» Si vote en cours, résultat = `*Cooldown*`

- Un placeholders permettant de savoir le nombre total de sites de votes. (`%azlink_vote_total_sites%`)

- Un placeholders permettant de savoir le nombre de votes disponible. (`%azlink_vote_total_available%`)
» Si tous les sites disponibles, résultat = `*Total*`
» Si aucun site disponible, résultat = `False`

- Un placeholders permettant de savoir si un site de vote en particulier est disponible. (`%azlink_vote_ID_available%`)
» Si site de vote disponible, résultat = `True`
» SI site de vote indisponible, résultat = `False`

- Un placeholder permettant de récupérer le pseudo du classement. (`%azlink_vote_name_[1-10]%`)

- Un placeholder permettant de récupérer la position d'un joueur du classement. (`%azlink_vote_position_[1-10]%`)

--> **Précision** : Je ne liste pas les votes totaux, mensuels ou autre car ça reste entièrement possible avec des plugins.

--------------
🇬🇧 **Hello, here I am with a new suggestion!**
I remembered that [AzLink](https://github.com/Azuriom/AzLink) offered a placeholder for the store currency defined in the Admin Panel, so it gave me an idea of placeholders that would help more than one with the [Azuriom Vote](https://github.com/Azuriom/Plugin-Vote) plugin, let me explain,
The idea I had is to add different placeholders related to votes, such as :

- A placeholder allowing to know the delay of a vote. (`%azlink_vote_ID_cooldown%`)
» If vote available, result = `True`
» If vote in progress, result = `*Cooldown*`

- A placeholder for the total number of voting sites (`%azlink_vote_total_sites%`)

- A placeholder to know the number of available votes. (`%azlink_vote_total_available%`)
» If all sites available, result = `*Total*`
» If no sites available, result = `False`

- A placeholder for whether a particular voting site is available. (`%azlink_vote_ID_available%`)
» If voting site available, result = `True`
» If voting site unavailable, result = `False`

- A placeholder to retrieve the nickname of the leaderboard. (`%azlink_vote_name_[1-10]%`)

- A placeholder to get the position of a player in the leaderboard. (`%azlink_vote_position_[1-10]%`)

--> **Note**: I don't list total votes, monthly or otherwise, as this is entirely possible with plugins.

**Comment by HamtaBot** [comment]
Bonjours @NoltoxGit je voudrais savoir si tu pouvais rajouter un exemple de placeholder , les deux que j’ai en tête permettraient de faire un top voteurs donc un qui retourne un pseudo et l’autre une valeur

**Comment by NoltoxGit** [comment]
> Bonjours @NoltoxGit je voudrais savoir si tu pouvais rajouter un exemple de placeholder , les deux que j’ai en tête permettraient de faire un top voteurs donc un qui retourne un pseudo et l’autre une valeur

Salut @amarcais53,
J'ai ajouté ta proposition dans mon issues, merci de ta suggestion !

Bonne journée à toi 😉

**Comment by MrJuju0319** [comment]
Salutation vous avez pu avancer sur ce projets ?

**Comment by MrMicky-FR** [comment]
Adding here some ideas from #45: for the shop it would be interesting to have placeholders for month goal and for top/recents donators

**Comment by MrMicky-FR** [comment]
Available in version 1.3.9 of AzLink 🚀 The lists of placeholders are available [here](https://github.com/Azuriom/AzLink?tab=readme-ov-file#placeholderapi-placeholders).
Just add this in your `config.yml`:
```yaml
# When PlaceholderAPI is installed, AzLink will register some placeholders
# that can be used in the server.
placeholders:
  # By default, %azlink_money% is registered and can be used to get the player's money.
  # If the Shop plugin is installed on the website, you can enable the shop placeholders.
  # The available placeholders are listed on https://github.com/Azuriom/AzLink#shop-placeholders
  shop: false

  # If the vote plugin is installed on the website, you can enable the vote placeholders.
  # The available placeholders are listed on https://github.com/Azuriom/AzLink#vote-placeholders
  vote: false

  # Duration format with placeholders for hours, minutes, and seconds.
  # Use %H/%M/%S for zero-padded (e.g. 03, 12) and %h/%m/%s for non-padded (e.g. 3, 12).
  # Example: "%H:%M:%S" for "01:30:05", and "%h h %m m %s s" for "1 h 30 m 5 s".
  duration-format: "%H:%M:%S"
```
