### ISSUE TITLE
More features for minecraft

### ISSUE THREAD

**Issue by xlanyleeet** [Azuriom/AzLink#45]
1. add broadcast message, who buy package like this
![image](https://github.com/Azuriom/AzLink/assets/61755593/a4945a28-5493-49d4-82ac-14d21ab0d0b7)
2. add {package} placeholder for site and plugin
3. add progress of fundraising and recent donations like this
![image](https://github.com/Azuriom/AzLink/assets/61755593/c50183c7-0d2a-47a9-9710-66074c4364b8)
4. Support of notification from site (many people don't notice notifications on the website, so it would be great if they were duplicated in the game itself)
5. Sync luckperms permission groups (site <-> server)

**Comment by MrMicky-FR** [comment]
Please take a look at existing placeholders before opening issues, which are directly below the command input for convenience:
![image](https://github.com/Azuriom/AzLink/assets/30863452/c513bfd2-6372-414e-b51d-436496887e39)

As shown above you already have `{package_name}` and `{package_id}` depending on your need, and for broadcast is most likely supported with the `broadcast` command on your server.

For the shop placeholders, I’ve added them in #16 👍

About bi-directional role sync, as discussed on Discord it would introduce some synchronization issues if roles change both on the website and on the server roughly at the same time. But for the website -> server synchronization, commands can be used like in the shop

**Comment by xlanyleeet** [comment]
> Please take a look at existing placeholders before opening issues, which are directly below the command input for convenience:

See in ua language dont have this (need update crowdin)
![image](https://github.com/Azuriom/AzLink/assets/61755593/1d90871b-f848-468c-8726-f4445400a755)



> For the shop placeholders, I’ve added them in #16 👍

okay, then wait



> About bi-directional role sync, as discussed on Discord it would introduce some synchronization issues if roles change both on the website and on the server roughly at the same time. But for the website -> server synchronization, commands can be used like in the shop

Yes, but this does not exclude the fact that this function is not necessary, when most of these cms with their own plugins have this function, you just need to think about how to do it, I think it's not difficult

**Comment by MrMicky-FR** [comment]
> See in ua language dont have this (need update crowdin)

It’s the `:placeholders` on your screen, which are automatically replaced by all the available placeholders (so translations doesn’t need to be updated every time a new placeholder is added).

Just checked and seems like this string was translated on Crowdin after the last Azuriom update, so it will be updated in the next Azuriom update 👍

> Yes, but this does not exclude the fact that this function is not necessary, when most of these cms with their own plugins have this function, you just need to think about how to do it, I think it's not difficult

The plugin (and also Azuriom) is fully open-source, if it’s not difficult a pull-request which handles gracefully these edge-cases (even not so edgy) would definitely be accepted 🙂

**Comment by MrMicky-FR** [comment]
Shop placeholders are now available in version 1.3.9 of AzLink 🚀 The lists of placeholders are available [here](https://github.com/Azuriom/AzLink?tab=readme-ov-file#placeholderapi-placeholders).

This allows to include top donators, recent purchases and donation goal in scoreboards, holograms and playerlist, for example:

<img width="344" height="344" alt="Image" src="https://github.com/user-attachments/assets/58f69ef4-cecb-42aa-8c9f-50cf0ee3315d" />
<img width="491" height="355" alt="Image" src="https://github.com/user-attachments/assets/48229cbb-8f02-485f-ad53-4df7ff3d064e" />

Just add this in your `config.yml`:
```yaml
# When PlaceholderAPI is installed, AzLink will register some placeholders
# that can be used in the server.
placeholders:
  # By default, %azlink_money% is registered and can be used to get the player's money.
  # If the Shop plugin is installed on the website, you can enable the shop placeholders.
  # The available placeholders are listed on https://github.com/Azuriom/AzLink#shop-placeholders
  shop: false

  # If the vote plugin is installed on the website, you can enable the vote placeholders.
  # The available placeholders are listed on https://github.com/Azuriom/AzLink#vote-placeholders
  vote: false

  # Duration format with placeholders for hours, minutes, and seconds.
  # Use %H/%M/%S for zero-padded (e.g. 03, 12) and %h/%m/%s for non-padded (e.g. 3, 12).
  # Example: "%H:%M:%S" for "01:30:05", and "%h h %m m %s s" for "1 h 30 m 5 s".
  duration-format: "%H:%M:%S"
```
